---
  general_settings:
    #Selecione a resulução, disponiveis:
    #1 - 1366x768
    #2 - 1680x1050
    #3 - 1920x1080
    resolution: 1

  # Bot configuration values
  ship_settings:
    # Total number of ships (total)
    empty_qtd_spaceships: 45
    
    # How many ships do you want to join the boss
    qtd_send_spaceships: 15

    # If you want to surrender, change it to the boss value (zero doesn't do it)
    boss_surrender: 7
    
    # Only send ships 100% (True/False)
    send_ships_full: False

    # If you want me to remove ships before adding others (True/False)
    remove_ships: True

    # Return to spaceship on waves 9, 14 and 19
    key_waves: True

    # Returns to ship selections whenever you finish surrender
    select_spaceship_after_surrender: True

    # Send only regular ships into battle
    send_only_common: False # Comming soon

    # Capture the rewards of each boss (average value and multiplier)
    get_rewards: True

    # Timeout to refresh the screen if no action was found. Default value 360 (6min)
    refresh_page: 360

  optimization_settings:    
    # Time between clicks (if bad connection increase this value) Default value: 0.6
    time_click: 0.05

    # Mouse travel speed (default 0.1)
    move_speed_mouse: 0.1
    
    # Leave the max-ammo filter always on
    set_filter_max_ammo: True

  # Confidence value of comparisons
  threshold:
    # Standard value: 0.7
    default: 0.7

    # Standard value: 0.8
    commom: 0.8
    
    # Standard value 0.9
    hard: 0.9

    # Standard value: 0.8
    select_wallet_buttons: 0.8

    # Standard value: 0.92
    go-fight: 0.92

    # Standard value: 0.95
    green_bar: 0.95

    # Standard value 0.98
    15-15-ships: 0.98

    # Standard value 0.98
    0-15: 0.98

    # Standard value 0.8
    confirm-end-boss: 0.8

    # Ships rarity. Standard value 0.92
    ships_rarity: 0.92

    # Rewards 
    rewards: 0.9
# Average reward value MEDIA for each boss. Base withdrawn on 21/02/22 (subject to change)
  rewards:
    boss_1: 0.09
    boss_2: 0.11
    boss_3: 0.13
    boss_4: 0.19
    boss_5: 0.18
    boss_6: 0.13
    boss_7: 0.20
    boss_8: 0.27
    boss_9: 0.35
    boss_10: 0.66
    boss_11: 0.50
    boss_12: 0.60
    boss_13: 0.66
    boss_14: 0.72
    boss_15: 1.08
    boss_16: 0.95
    boss_17: 0.96
    boss_18: 1.14
    boss_19: 1.04
    boss_20: 1.95